#!/bin/bash

# Script senzill que utilitza stdin, stdout y stderr

echo "Introdueix el teu nom:"  # stdout
# Utilitzem echo per imprimir un missatge en la sortida estàndard (stdout).

read nom  # stdin
# Utilitzem read per llegir el nom des de l'entrada estàndard (stdin).

if [ -z "$nom" ]; then
    echo "Error: El nom no pot estar buit." >&2  # stderr
# Verifiquem si el nom està buit i emetem un missatge d'error 
# en la sortida estàndard (stderr) si és el cas.

    exit 1
fi

echo "Hola, $nom. ¡Benvingut!"  # stdout

echo "Aquest és un missatge normal."  # stdout

# Simula un error y emet un missatge a stderr
echo "Això és un missatge d'error." >&2  # stderr

# >& és la sintaxis per redirigir un flux (stream) a 
# un altre descriptor d’arxiu (0 és stdin, 1 és stdout i 2 is stderr)

echo "Fi de l'script"
